Diploma
EugeneSavchits/diploma pull request #1
Opened 2022-04-11 13:01 UTC by EugeneSavchits

2022-04-28 10:38 UTC, wildpioneer requested changes

2022-04-28 10:38 UTC, wildpioneer commented on src/main/java/baseEntities/BaseApiTest.java
>                  .header(HTTP.CONTENT_TYPE, ContentType.JSON) //указание в каком формате будут приходить данные
Удалить все комментарии, которые делалилсь на занятиях и не относятся к проекту

2022-04-28 10:38 UTC, wildpioneer commented on src/main/java/baseEntities/BaseApiTest.java
> +                .auth().preemptive().basic(ReadProperties.getUsername(), System.getProperty("PASSWORD")); //метод preemptive() для старых сайтов, для новых только basic()
Для чего сделана вычитка из системный переменных? Просто в parallel.xml я не вижу передаваемых параметров

2022-04-28 10:38 UTC, wildpioneer commented on src/test/java/pages/AddTestCasePage.java
> +
fileUpload - мне не нравиться xpath который там написан - спецсимвол в текстовом поиске - это плохо

2022-04-28 10:38 UTC, wildpioneer commented on src/test/java/tests/DataNegativeTest.java
> -
new StringSelection("C:\\Users\\Lenovo\\Downloads\\Lesson_24 CICD.mp4"); - нельзя использовать абсолютный путь - только относительный

2022-05-04 12:27 UTC, EugeneSavchits commented on src/main/java/baseEntities/BaseApiTest.java
>                  .header(HTTP.CONTENT_TYPE, ContentType.JSON) //указание в каком формате будут приходить данные
Удалил

2022-05-04 12:30 UTC, EugeneSavchits commented on src/main/java/baseEntities/BaseApiTest.java
> +                .auth().preemptive().basic(ReadProperties.getUsername(), System.getProperty("PASSWORD")); //метод preemptive() для старых сайтов, для новых только basic()
Значение системной переменной я передаю когда запускаю через Jenkins 
(// To run Maven on a Windows agent, use
                bat "mvn -Dmaven.test.failure.ignore=true, -DPASSWORD=bcDS.C6cBKSceVGifQHD clean test")

2022-05-04 12:31 UTC, EugeneSavchits commented on src/test/java/pages/AddTestCasePage.java
> +
Переписал xpath

2022-05-04 12:32 UTC, EugeneSavchits commented on src/test/java/tests/DataNegativeTest.java
> -
С относительным путем Робот не работает, файл получилось загрузить только через Робота

2022-05-05 10:46 UTC, wildpioneer commented on src/test/java/tests/DataNegativeTest.java
> -
В таком случае - надо путь строить в коде - а именно:
1. Положить файл в Resources
2. Получить путь к файлу например:
String pathToFile = ActionsTest.class.getClassLoader().getResource("download.jpeg").getPath();

<ActionsTest> - имя класса в котором это вызывается
<download.jpeg> - имя файла который загружаем и он лежит в test/resources

2022-05-12 13:38 UTC, EugeneSavchits commented on src/test/java/tests/DataNegativeTest.java
> -
Сделал немного по другому File file = new File("src/test/resources/data/oboi_pogonia.jpg");
        String absolutePath = file.getAbsolutePath();
При вашем способе путь файла пишется с наклонными чертами не в ту сторону и слэш в начале пути файла ставится.
Посмотрите пожалуйста норм ли так будет?

2022-05-25 15:09 UTC, merged